name: HowToWpf build and test
on:
  push:
    paths:
      - .net/HowToWpf/HowToWpf
      - .github/workflows/HowToWpf.yaml
  workflow_dispatch:
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: .net/HowToWpf/HowToWpf
      runs-on: windows-latest